# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-10 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datewisetweets',
            name='name',
            field=models.CharField(max_length=140),
        ),
    ]
