# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-10 13:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitterApp', '0003_auto_20171210_1225'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
